env:
  global:
    - secure: JblaEHG8j4ygEfuRgi6VfLwaGyO+BVmGkdxIs1j5bwUJ1RcAZxAkqexDu5ElqUgNEXeUxNw77W6hjxAh7iSLLEozW+KjckpI7bm/F99VpM3xWD1joJN9MZSeAhdvb0K2mXjjeBLCX8q0+IJ9iUfCsMDDYsQWdo0u/beTox9HMD8=
  matrix:
    - FEATURES=""
    - FEATURES="snappy"
language: rust
sudo: false
os:
  - linux
  - osx
script:
  - cargo test --verbose --features "$FEATURES"
after_script:
  - cargo doc --verbose --features "snappy"
  - cp -R target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
  - rm -r doc
