[package]

name = "leveldb"
version = "0.0.1"
authors = ["Andrew Dunham <andrew@du.nham.ca>"]
build = "make libs_for_cargo"

[dependencies.error]
git = "https://github.com/reem/rust-error.git"
rev = "1bdbe0848ea14ce8812e279066f5fda48e9790ac"
